---
title: "Analysis of Yost dataset"
author: "Massimo Andreatta & Laura Yerly"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE,fig.width=16,fig.height=12}
renv::restore()
library(Seurat)
library(ggplot2)
```

# Read in count matrices and metadata

Download from GEO (GSE123813):  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE123813 
```{r}
fname <- "./Yost_data/GSE123813_bcc_scRNA_counts.txt"

Yost_counts <-  read.table(fname, header = TRUE, dec =".",sep = "\t",as.is = TRUE)
```

Import metadata 
```{r}
fname <- "./Yost_data/GSE123813_bcc_all_metadata.txt"

Metadata <- read.table(fname,sep = "\t", header = TRUE, dec =".")

rownames(Metadata) <- Metadata$cell.id
```

# Create a seurat object 
```{r}
library(STACAS)
data(EnsemblGeneTable.Hs)

options("Seurat.object.assay.version" = "v3")
Yost_BCC <- CreateSeuratObject(counts = Yost_counts, project = "BCC_Yost",
                               min.cells = 3, min.features = 50)

Yost_BCC <- StandardizeGeneSymbols(Yost_BCC, slots = "counts", EnsemblGeneTable = EnsemblGeneTable.Hs)
```

# Add metadata
```{r}
Yost_BCC <- AddMetaData(Yost_BCC, metadata = Metadata)

table(Yost_BCC$patient, Yost_BCC$treatment)
Yost_BCC$Sample <- paste(Yost_BCC$patient, Yost_BCC$treatment, sep = "_")
```

# QC
Dissociation-related genes
```{r}
dissoc_genes <- c("Actg1__chr11","Ankrd1__chr19","Arid5a__chr1","Atf3__chr1","Atf4__chr15","Bag3__chr7","Bhlhe40__chr6",
                  "Brd2__chr17","Btg1__chr10","Btg2__chr1","Ccnl1__chr3","Ccrn4l__chr3","Cebpb__chr2","Cebpd__chr16",
                  "Cebpg__chr7","Csrnp1__chr9","Cxcl1__chr5","Cyr61__chr3","Dcn__chr10","Ddx3x__chrX","Ddx5__chr11",
                  "Des__chr1","Dnaja1__chr4","Dnajb1__chr8","Dnajb4__chr3","Dusp1__chr17","Dusp8__chr7",
                  "Egr1__chr18","Egr2__chr10","Eif1__chr11","Eif5__chr12","Erf__chr7","Errfi1__chr4","Fam132b__chr1",
                  "Fos__chr12","Fosb__chr7","Fosl2__chr5","Gadd45a__chr6","Gcc1__chr6","Gem__chr4","H3f3b__chr11",
                  "Hipk3__chr2","Hsp90aa1__chr12","Hsp90ab1__chr17","Hspa1a__chr17","Hspa1b__chr17","Hspa5__chr2",
                  "Hspa8__chr9","Hspb1__chr5","Hsph1__chr5","Id3__chr4","Idi1__chr13","Ier2__chr8","Ier3__chr17",
                  "Ifrd1__chr12","Il6__chr5","Irf1__chr11","Irf8__chr8","Itpkc__chr7","Jun__chr4","Junb__chr8",
                  "Jund__chr8","Klf2__chr8","Klf4__chr4","Klf6__chr13","Klf9__chr19","Litaf__chr16","Lmna__chr3",
                  "Maff__chr15","Mafk__chr5","Mcl1__chr3","Midn__chr10","Mir22hg__chr11","Mt1__chr8","Mt2__chr8",
                  "Myadm__chr7","Myc__chr15","Myd88__chr9","Nckap5l__chr15","Ncoa7__chr10","Nfkbia__chr12","Nfkbiz__chr16",
                  "Nop58__chr1","Nppc__chr1","Nr4a1__chr15","Odc1__chr12","Osgin1__chr8","Oxnad1__chr14","Pcf11__chr7",
                  "Pde4b__chr4","Per1__chr11","Phlda1__chr10","Pnp__chr14","Pnrc1__chr4","Ppp1cc__chr5","Ppp1r15a__chr7",
                  "Pxdc1__chr13","Rap1b__chr10","Rassf1__chr9","Rhob__chr12","Rhoh__chr5","Ripk1__chr13","Sat1__chrX",
                  "Sbno2__chr10","Sdc4__chr2","Serpine1__chr5","Skil__chr3","Slc10a6__chr5","Slc38a2__chr15",
                  "Slc41a1__chr1","Socs3__chr11","Sqstm1__chr11","Srf__chr17","Srsf5__chr12","Srsf7__chr17",
                  "Stat3__chr11","Tagln2__chr1","Tiparp__chr3","Tnfaip3__chr10","Tnfaip6__chr2","Tpm3__chr3",
                  "Tppp3__chr8","Tra2a__chr6","Tra2b__chr16","Trib1__chr15","Tubb4b__chr2","Tubb6__chr18",
                  "Ubc__chr5","Usp2__chr9","Wac__chr18","Zc3h12a__chr4","Zfand5__chr19","Zfp36__chr7","Zfp36l1__chr12",
                  "Zfp36l2__chr17","Zyx__chr6","Gadd45g__chr13","Hspe1__chr1","Ier5__chr1","Kcne4__chr1")
dissoc_genes <- toupper(sapply(dissoc_genes, function(x){
  strsplit(x, "__")[[1]][1]
}))
length(dissoc_genes) # 140
head(dissoc_genes)
```

```{r define_qc_metrics}
#Get mitochondrial and ribosomal signatures
library(SignatuR)
ribo.genes <- GetSignature(SignatuR$Hs$Compartments$Ribo)
mito.genes <- GetSignature(SignatuR$Hs$Compartments$Mito)

# Compute ribosomal and mitochondrial content and add to Seurat object metadata
Yost_BCC <- AddMetaData(Yost_BCC, metadata = PercentageFeatureSet(Yost_BCC, features = ribo.genes[ribo.genes %in% rownames(Yost_BCC)]), col.name = "percent.ribo")

Yost_BCC <- AddMetaData(Yost_BCC, metadata = PercentageFeatureSet(Yost_BCC, features = mito.genes[mito.genes %in% rownames(Yost_BCC)]), col.name = "percent.mito")

Yost_BCC <- AddMetaData(Yost_BCC, metadata = PercentageFeatureSet(Yost_BCC, features = dissoc_genes[dissoc_genes %in% rownames(Yost_BCC)]), col.name = "percent.dissoc")

# Compute the ratio of number of genes/features and number of counts/UMIs
Yost_BCC$log10GenesPerUmi <- log10(Yost_BCC$nFeature_RNA) / log10(Yost_BCC$nCount_RNA)

```




```{r qc_plots0, fig.height= 10}
Idents(Yost_BCC) <- "Sample"
VlnPlot(Yost_BCC,
        features = c("nFeature_RNA", "nCount_RNA",
                     "percent.ribo","percent.mito",
                     "percent.dissoc","log10GenesPerUmi"),
        ncol = 3, pt.size=0)
```


### Custom thresholds

```{r set_cutoffs}
cutoffs <- list()
cutoffs[["percent.ribo"]] <- c(min=0,max=60)
cutoffs[["percent.mito"]] <- c(min=0,max=15)
cutoffs[["nFeature_RNA"]] <- c(min=500,max=5000) 
cutoffs[["nCount_RNA"]] <- c(min=800,max=30000)
cutoffs[["percent.dissoc"]] <- c(min=0, max=15)
cutoffs[["log10GenesPerUmi"]] <- 0.7
print(cutoffs)
```

### Standard check

```{r probs}
for(va in names(cutoffs)){
  cat(va, "\n")
  print(quantile(Yost_BCC@meta.data[[va]],
                 probs=c(0.001, 0.005, 0.01, 0.02,
                         0.98, 0.99, 0.995, 0.999))
        )
}
```



```{r subset_seurat fig.height= 10}
# store initial number of cells
initialCellNum <- ncol(Yost_BCC)
message(paste("Original number of cells:", initialCellNum))

# Perform subsetting using cutoffs list and qc metrics considered
Yost_BCC <- subset(Yost_BCC, subset = 
                        nFeature_RNA >= cutoffs[["nFeature_RNA"]]["min"] &
                        nFeature_RNA < cutoffs[["nFeature_RNA"]]["max"] & 
                        nCount_RNA   >= cutoffs[["nCount_RNA"]]["min"]   & 
                        nCount_RNA   < cutoffs[["nCount_RNA"]]["max"]   &  
                        percent.ribo >= cutoffs[["percent.ribo"]]["min"] & 
                        percent.ribo < cutoffs[["percent.ribo"]]["max"] &
                        percent.mito >= cutoffs[["percent.mito"]]["min"] &
                        percent.mito < cutoffs[["percent.mito"]]["max"] &
                        percent.dissoc >= cutoffs[["percent.dissoc"]]["min"] &
                        percent.dissoc < cutoffs[["percent.dissoc"]]["max"] &
                        log10GenesPerUmi > cutoffs[["log10GenesPerUmi"]]
                      )

# Print and evaluate the cell drop out after filtering
l <- ncol(Yost_BCC)
message(sprintf("Number of cells after QC: %i (%.2f %% of input)", l, 100*l/initialCellNum))
```



```{r}
set.seed(123)
Yost_BCC <- NormalizeData(Yost_BCC) |> FindVariableFeatures(nfeatures = 2000, verbose = FALSE)
Yost_BCC <- ScaleData(Yost_BCC) |> RunPCA(npcs = 30) |>
  RunUMAP(reduction = "pca", dims = 1:30)

Yost_BCC <- FindNeighbors(Yost_BCC, dims = 1:30) |> FindClusters(resolution=2)
```

```{r fig.height=8, fig.width=12}
a <- DimPlot(Yost_BCC, group.by = "patient") + theme(aspect.ratio = 1)
b <- DimPlot(Yost_BCC, group.by = "Sample") + theme(aspect.ratio = 1)
a | b
```

##Broad classification using scGate

```{r}
library(scGate)

models.DB <- scGate::get_scGateDB()
models.list <- models.DB$human$TME_HiRes

models.list$Melanocyte <- gating_model(name = "Melanocyte", signature = c("PMEL","MLANA","LYZ-"))

Yost_BCC <- scGate(Yost_BCC, model = models.list, ncores = 8, multi.asNA = T)
```

```{r}
ann <- DimPlot(Yost_BCC, group.by = "scGate_multi", label = T, repel = T, label.size = 2) +
    theme(aspect.ratio = 1) + ggtitle("scGate annotation")
ann
```

```{r fig.width=12}
a | ann
```


```{r}
table(Yost_BCC$Sample, Yost_BCC$scGate_multi, useNA = "ifany")
```

# Save 
```{r}
file <- "cache/Yost_BCC_all.rds"

saveRDS(object = Yost_BCC, file=file)
```
